[workspace]
members = [
    "apps/*/src-tauri",
    "apps/tui",
    "crates/filesystem",
    "crates/infrastructure",
    "crates/llm",
    "crates/ai-providers/*",
    "crates/ai-providers/ollama/benchmark",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
