[package]
name = "filesystem"
version = "0.0.1"
edition = "2024"

[dependencies]
atomic-write-file = "0.3.0"
thiserror = "2.0"
tokio = { version = "1.53.1", features = ["fs", "io-util", "rt", "sync"] }

[dev-dependencies]
tempfile = "3.23.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
